# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
# 当前分支，adm64为稳定，~amd64为最新
ACCEPT_KEYWORDS="~amd64"
# 为所语言设置编译标志
#COMMON_FLAGS="-march=native -O3 -pipe"
COMMON_FLAGS="-mtune=skylake -march=skylake -O3 -pipe"
# 为两个变量使用相同的设置
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"


# 优化Rust CPU编译
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
export CARGO_BUILD_JOBS=3


# 调试日志
#DISTCC_VERBOSE=1


FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8


# 设置软件许可证
ACCEPT_LICENSE="* -@EULA"

# 签名？
USE="modules-sign"
# Optionally, to use custom signing keys.
MODULES_SIGN_KEY="/path/to/kernel_key.pem"
MODULES_SIGN_CERT="/path/to/kernel_key.pem" # Only required if the MODULES_SIGN_KEY does not also contain the certificate.
MODULES_SIGN_HASH="sha512" # Defaults to sha512.

# 使用自定义内核
#USE="dist-kernel"

GIT_CEILING_DIRECTORIES="/"
