# created by eselect-repo
[haskell]
location = /var/db/repos/haskell
sync-type = git
sync-uri = https://github.com/gentoo-haskell/gentoo-haskell.git

[janus]
location = /var/db/repos/janus
sync-type = git
sync-uri = https://github.com/janusssss/overlay.git
