# 如果未定义，Portage 的默认行为是：
# - 将 MAKEOPTS jobs 值设置为与 'nproc' 返回的相同线程数
# - 将 MAKEOPTS load-average 值设置为略高于 'nproc' 返回的线程数，因为它是一个阻尼值
# 请根据系统需要替换 '4' （使用系统线程数或GB记内存除以二的最小值），或者不设置。
# -j = distcc+local/2
MAKEOPTS="-j 10 -l 11"

# 兼容steam
USE="abi_x86_32"
